### Site info:
title: Daniel Maina
tagline: The intersection between my work and passions
author: Daniel Maina
email: fofungi@gmail.com
description: "This blog is powered by jekyll and templated by yulijia ." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Business, Information, management,Security, Data, Life"
baseurl: /sampleblog # the subpath of your blog.
url: "http://yulijia.net/freshman21" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: daniel_maina
github_username:  danmyner
disqus_shortname: freshman21
favicon:     "/images/favicon.ico"
aboutme: Hi, this is Daniel Maina. I am here to share knowledge and more importantly, to learn. I also believe that work can be fun. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Daniel Maina
      href: http://yulijia.net/freshman21
      title: Another Perspective to life and work
    - name: author's website
      href: www.danielmaina.me
      title: My website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
